//! T2 — worked examples for the manual, produced by running the commands.
//!
//! # Why generated
//!
//! `Documentation/CLI.md` documents 28 items and, until 1.2.0, showed almost no
//! complete invocation. It answers *what does this field mean* for a reader who
//! already knows what to type; it did not answer *what does this look like*.
//!
//! The obvious fix is to paste some output into the manual. This repository has
//! learned what that costs twice in one year: `D-A16` sat recorded and unapplied
//! in the normative specification for two releases, and the `NASA_FACT_SHEET`
//! citation pointed at a URL that had stopped resolving. Both were copies, and
//! both drifted silently because nothing compared them with the thing they
//! described.
//!
//! So the examples are generated by **executing the commands** and capturing
//! what they print, and `check-docs` fails if the committed file is not what a
//! fresh run produces. An example cannot show output the program does not
//! produce, and a change in output is a failing build rather than a
//! documentation bug nobody notices.
//!
//! # Why a separate file
//!
//! `CLI-EXAMPLES.md` rather than injection into `CLI.md`, because a generator
//! that rewrites a hand-written file in place has to be trusted with the
//! hand-written parts. `CLI.md` links to it. The generated file says at the top
//! that it is generated, since a reader who edits it will otherwise lose the
//! edit at the next `gen-examples`.
//!
//! # What is deliberately not here
//!
//! `now` and `tour`'s clock-dependent output. `now` reads the system clock, so
//! its output differs on every run and could never match a committed file; the
//! manual documents it and the examples skip it, which is stated in the file
//! rather than left as an unexplained absence.

use std::path::Path;
use std::process::Command;

/// One example: a command line, and why a reader is being shown it.
struct Example {
    args: &'static [&'static str],
    why: &'static str,
}

const T: &str = "8070205189123984864657505252035637180530466139316558837890625";

fn examples() -> Vec<Example> {
    vec![
        Example {
            args: &["datum"],
            why: "What tick 0 is, and — more of the output than a reader expects — what is *not* being claimed about it.",
        },
        Example {
            args: &["explain", T],
            why: "One instant in every form the program has. The 61-digit integer is the value; everything under it is a rendering of that same number.",
        },
        Example {
            args: &["explain", T, "--why"],
            why: "The same document with each field annotated by the rule or section that requires it. Almost nothing here is a convenience.",
        },
        Example {
            args: &["between", "0", T, "--at", "beat"],
            why: "A duration on the tier ladder. `--at` adds the whole count and remainder at one named tier.",
        },
        Example {
            args: &["--bridge", "between", "0", T],
            why: "The same difference with the SI conversion asked for. Without `--bridge` no Earth unit appears, which is the project's whole argument in one flag.",
        },
        Example {
            args: &["ladder", "--named-only"],
            why: "The ten named rungs of the 45-tier grid. A tier's identity is its exponent; the names are display-only.",
        },
        Example {
            args: &["cal", "list"],
            why: "Seven derived calendars, two with anchors. A body without an anchor is the ordinary case, not a failure.",
        },
        Example {
            args: &["cal", "show", "earth-d", T],
            why: "One derived calendar in full: its intercalation, its cycles, and the cited anchor that gives it a phase.",
        },
        Example {
            args: &["show", T],
            why: "One instant in several calendars at once, each labelled derived or legacy.",
        },
        Example {
            args: &["events", "show", "recombination"],
            why: "A cited milestone. Events are intervals, and the citation travels with the value.",
        },
        Example {
            args: &["timeline"],
            why: "The catalogue against the tier ladder — the whole of time on one screen.",
        },
        Example {
            args: &["cosmo", "age", "--z", "1100", "--depth", "8"],
            why: "A certified enclosure by integer quadrature. Depth 8 keeps this example fast; `CLI.md` has the cost table.",
        },
        Example {
            args: &["verify"],
            why: "The binary re-deriving the constants it ships with, and saying plainly that agreeing with itself is not verification.",
        },
        Example {
            args: &["doctor"],
            why: "Which profile, which backend, which features — the first thing to paste into a bug report.",
        },
        Example {
            args: &["to-civil", T, "--digits", "3"],
            why: "An Earth calendar label. This is an Earth command, so it carries Earth units unasked.",
        },
        Example {
            args: &["from-civil", "2026-08-07"],
            why: "And back. Exact or an error, never rounded.",
        },
        // The wall clock, as a frame. Deterministic because `--once --at`
        // fixes the instant and `COLUMNS` fixes the width, which is the whole
        // reason `--once` exists: until it did, the only thing holding a claim
        // about the clock's appearance was a test that greps a buffer, and
        // nobody reading the documentation could see a face.
        Example {
            args: &["wallclock", "--once", "--at", T, "--theme", "startrek", "--height", "26"],
            why: "LCARS. The elbow, the rail of tier readouts, the beat in block digits, and the flicker as a bar because a number would be wrong before it was drawn.",
        },
        Example {
            args: &["wallclock", "--once", "--at", T, "--theme", "starwars", "--height", "24"],
            why: "A targeting computer: canopy brackets, a reticle round the beat, the flicker riding the crosshair, and every other hand compressed into one strip. An instrument, where LCARS is a console.",
        },
        Example {
            args: &["wallclock", "--once", "--at", T, "--gagarin", "--locale", "ru", "--height", "24"],
            why: "A Vostok instrument panel: an enamelled plate with bezelled gauges set into it, engraved labels, and a red lamp. Cyrillic chrome; the tier names follow --locale, which is why this example passes one.",
        },
        Example {
            args: &["wallclock", "--once", "--at", T, "--armstrong", "--height", "24"],
            why: "An Apollo DSKY. VERB 16 NOUN 65 is a real pair — monitor, decimal, time — and the lamps are drawn unlit except COMP ACTY, because the rest report conditions this program does not have.",
        },
        Example {
            args: &["wallclock", "--once", "--at", T, "--clock-local", "mars-d", "--height", "20"],
            why: "The plain theme with a second dial. A wall clock's second face has always shown another place, and Mars is one.",
        },
        Example {
            args: &["explain", "abc"],
            why: "A rejection: an Appendix E code, an exit status, and — since 1.2.0 — what a good input would have looked like.",
        },
    ]
}

/// Run one example against the built binary and return its output.
fn capture(bin: &Path, args: &[&str]) -> Result<String, String> {
    // `wallclock` needs the non-default `tui` feature. A binary without it
    // rejects the subcommand, and the resulting file would silently document a
    // program that is missing a command — so this is an error and names the fix.
    let out = Command::new(bin)
        .args(args)
        .env("NO_COLOR", "1")
        // A fixed width, so the committed file does not depend on the terminal
        // that generated it.
        .env("COLUMNS", "80")
        .output()
        .map_err(|e| format!("{}: {e}", bin.display()))?;
    let mut text = String::from_utf8_lossy(&out.stdout).into_owned();
    let err = String::from_utf8_lossy(&out.stderr);
    if err.contains("unrecognized subcommand") || err.contains("unexpected argument") {
        return Err(format!(
            "`ucal {}` was rejected by the binary: it is probably built without \
             `--features tui`. Run `cargo build --release -p ucal --features tui`.",
            args.join(" ")
        ));
    }
    if !err.trim().is_empty() {
        text.push_str(err.trim_end());
        text.push('\n');
    }
    Ok(text)
}

/// Build the examples document.
pub fn generate(root: &Path, bin: &Path) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("# Worked examples\n\n");
    out.push_str("**Generated — do not edit.** Every block below is the real output of the command above it, captured by running it. Regenerate with:\n\n");
    out.push_str("```\ncargo build --release -p ucal --features tui\ncargo run -p xtask -- gen-examples\n```\n\n");
    out.push_str("`cargo run -p xtask -- check-docs` fails if this file is not what a fresh run produces, so an example cannot describe output the program does not produce. Field-by-field documentation is in [`CLI.md`](CLI.md).\n\n");
    out.push_str("`ucal now` and `ucal tour` are absent on purpose: `now` reads the system clock, so its output differs on every run and could never match a committed file.\n\n");
    out.push_str("Colour is off and the width is 80 columns, so these match a redirected run rather than a terminal.\n\n---\n");

    for ex in examples() {
        let text = capture(bin, ex.args)?;
        out.push_str(&format!("\n## `ucal {}`\n\n{}\n\n```\n{}```\n", ex.args.join(" "), ex.why, text));
    }
    let _ = root;
    Ok(out)
}

fn path_of(root: &Path) -> std::path::PathBuf {
    root.join("Documentation/CLI-EXAMPLES.md")
}

/// The release binary, which must exist before the examples can be generated.
fn binary(root: &Path) -> Result<std::path::PathBuf, String> {
    let bin = root.join("target/release/ucal");
    if bin.exists() {
        Ok(bin)
    } else {
        Err(format!(
            "{} is missing; run `cargo build --release -p ucal --features tui` first",
            bin.display()
        ))
    }
}

/// Write the examples file.
pub fn write(root: &Path) -> Result<std::path::PathBuf, String> {
    let bin = binary(root)?;
    let text = generate(root, &bin)?;
    let path = path_of(root);
    std::fs::write(&path, text).map_err(|e| format!("{}: {e}", path.display()))?;
    Ok(path)
}

/// Fail if the committed examples are not what a fresh run produces.
///
/// Skipped, with a message, when the release binary is absent: this check needs
/// a built program and `check-docs` must stay runnable on a clean checkout.
/// Saying so is the point — a check that silently passes when it cannot run is
/// how a stale file survives.
///
/// # It can fail for a reason that is not a defect
///
/// The binary it runs is whatever is at `target/release/ucal`, and nothing here
/// knows whether that is current. A tree whose sources have moved since the last
/// `cargo build --release` produces a **false failure**: the committed file is
/// correct and the binary is old.
///
/// That happened during 1.4.0 and cost a few minutes of looking for a defect
/// that was not there. CI never sees it — every run builds from scratch — so
/// this is a local-only trap, and the failure message names the fix rather than
/// the diagnosis, which is why it reads as worse than it is.
///
/// Not solved by having this build the binary: `check-docs` would then take
/// minutes instead of milliseconds, and a check nobody runs because it is slow
/// is worse than one that occasionally misreports. Recorded instead, and the
/// release procedure builds first.
pub fn check(root: &Path) -> Result<Option<usize>, String> {
    let Ok(bin) = binary(root) else {
        return Ok(None);
    };
    let want = generate(root, &bin)?;
    let path = path_of(root);
    let have = std::fs::read_to_string(&path)
        .map_err(|_| format!("{} is missing; run `cargo run -p xtask -- gen-examples`", path.display()))?;
    if have == want {
        Ok(Some(examples().len()))
    } else {
        Err(format!(
            "{} does not match what target/release/ucal produces.\n          \
             If sources changed since the last release build, that binary is \
             stale and this is a false alarm: `cargo build --release -p ucal` \
             first.\n          Otherwise: `cargo run -p xtask -- gen-examples`",
            path.display()
        ))
    }
}
